# Assignmnet 04-06-20

# CSE-221710305032-M.Sai Srinivas

Question 1:<br>[Reversing an Array] <br>Write a NumPy program to reverse an array (first element becomes last). <br>Original array:<br>[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]<br>Reverse array:<br>[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]


In [3]:
import numpy as np
array=np.arange(12,38)
rev_array=array[::-1]
print("original Array:\n",array)
print("Reverse Array:\n",rev_array)

original Array:
 [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse Array:
 [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


Question 2:<br>[Make Border 1] <br>Write a NumPy program to create a 2d array with 1 on the border and 0 inside. <br>Original array:<br>[[ 1. 1. 1. 1. 1.]<br>...................<br>[ 1. 1. 1. 1. 1.]]<br>1 on the border and 0 inside in the array<br>Expected output:<br>[[ 1. 1. 1. 1. 1.]<br> [1. 0. 0. 0. 1.]<br>……………..<br> [1. 0. 0. 0. 1.]<br>[ 1. 1. 1. 1. 1.]]


In [26]:
m,n=input("Enter rows and colums: ").split()
array=np.ones((int(m),int(n)))
array[1:-1,1:-1]=0
print(array)

Enter rows and colums: 5 8
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


Question 3:<br>[Membership Test] <br>Write a NumPy program to test whether each element of a 1-D array is also present in a second array.<br>Expected Output:<br>Array1: [ 0 10 20 40 60]<br>Array2: [0, 40]<br>Compare each element of array1 and array2<br>[ True False False True False]


In [31]:
ar1=input("enter array1: ").split()
ar1=[int(i) for i in ar1]
ar2=input("enter array2: ").split()
ar2=[int(i) for i in ar2]
arr1=np.array(ar1)
arr2=np.array(ar2)
f=np.vectorize(lambda x:x in arr2)
print(f(arr1))

enter array1: 0 10 20 40 60
enter array2: 0 40
[ True False False  True False]


Question 4:<br>[Set Difference] <br>Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.<br>Expected Output:<br>Array1: [ 0 10 20 40 60 80]<br>Array2: [10, 30, 40, 50, 70, 90]<br>Set difference between two arrays:<br>[ 0 20 60 80]


In [38]:
ar1=input("enter array1: ").split()
ar1=[int(i) for i in ar1]
ar2=input("enter array2: ").split()
ar2=[int(i) for i in ar2]
arr1=np.array(ar1)
arr2=np.array(ar2)
f=np.vectorize(lambda x:x not in arr2)
print(arr1[f(arr1)])

enter array1: 0 10 20 40 60 80
enter array2: 10 30 40 50 70 90
[ 0 20 60 80]


Question 5:<br>[Formation of Diagonal Matrix] <br>Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.<br>Expected Output:<br>[[4 0 0 0]<br>[0 5 0 0]<br>[0 0 6 0]<br>[0 0 0 8]]

In [56]:
lis=input("Enter values: ").split()
lis=[int(i) for i in lis]
ar=np.array(lis)
print(np.diag(ar))

Enter values: 4 5 6 8
[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]
